version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_order
    ports:
      - "5674:5672"
      - "15674:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  order:
    build:
      context: ./order
      dockerfile: Dockerfile
    container_name: api_order
    ports:
      - "8680:8580"
    environment:
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
      - DB_CONNECTION_STRING=mongodb://mongodb:27018/OrderDB
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - backend

  # order_tests:
  #   build:
  #     context: ./order
  #     dockerfile: Dockerfile.tests
  #   container_name: order_tests
  #   command: dotnet test --logger "console;verbosity=detailed"
  #   depends_on:
  #     - rabbitmq
  #     - mongodb
  #   networks:
  #     - backend

  mongodb:
    image: mongo
    container_name: mongodb_order
    ports:
      - "27019:27017"
    networks:
      - backend

networks:
  backend:
    driver: bridge
