apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - name: order-api
        image: knowcodera/techchallengefiaporder:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: order-api-config
        - secretRef:
            name: order-api-secret
