apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: order-api
        image: mycontainerregistrytechchallenge.azurecr.io/order:latest
        ports:
        - containerPort: 8580
