apiVersion: v1
kind: Service
metadata:
  name: order-api
spec:
  selector:
    app: order-api
  ports:
    - name: http
      protocol: TCP
      port: 8580
      targetPort: 8580
  type: LoadBalancer
