name: Build and Deploy Order API to Azure AKS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  ACR_NAME: ${{ secrets.AZURE_ACR_NAME }}
  RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  AKS_CLUSTER_NAME: ${{ secrets.AZURE_AKS_CLUSTER_NAME }}
  DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x' 

    - name: Clean Order API
      run: dotnet clean ./order/src/OrderApi/OrderApi.csproj

    - name: Restore dependencies for Order API
      run: dotnet restore ./order/src/OrderApi/OrderApi.csproj

    - name: Build Order API
      run: dotnet build ./order/src/OrderApi/OrderApi.csproj --configuration Release --no-restore

    - name: Run Unit Tests for Order API
      run: dotnet test ./order/src/OrderTests/OrderTests.csproj --configuration Release --no-restore --logger "console;verbosity=detailed"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry (ACR)
      uses: azure/docker-login@v1
      with:
         login-server: ${{ env.ACR_NAME }}.azurecr.io
         username: ${{ secrets.AZURE_CLIENT_ID }}
         password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Build and Push Docker image for Order
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/order:dev ./order
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/order:dev

    - name: Configure kubectl for AKS
      uses: azure/aks-set-context@v2
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}
       cluster-name: ${{ env.AKS_CLUSTER_NAME }}
       resource-group: ${{ env.RESOURCE_GROUP }}

    - name: Deploy Order API to AKS
      run: |
        kubectl apply -f .k8s/deployment-order.yaml
        kubectl apply -f .k8s/service-order.yaml
